[workspace]
# Use the newer version of the cargo resolver
# https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
members  = ["cli", "bar"]
resolver = "2"


[workspace.dependencies]
bar = { path = "./crates/bar", version = "0.1.3" }
