[packages.cli]
versioned_files = ["cli/Cargo.toml", "Cargo.lock"]
scopes = ["cli"]

[packages.bar]
versioned_files = ["bar/Cargo.toml", "Cargo.lock"]
scopes = ["bar"]

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"
ignore_conventional_commits = true

[[workflows.steps]]
type = "Command"
command = 'git commit -m "chore: prepare releases"'

[[workflows.steps]]
type = "Command"
command = "git push"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[github]
owner = "ematipico"
repo = "knope-test"
